layout_spectrum: 0.9342242085840553
typography_spectrum: 0.11379444552585483
color:
  brandStrength: 0.7967910207808018
  lightness: 0.03685718425549567
  saturation: 0.6242744042538106
  rhythmicContrast: 0.55457479855977
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
author:
  name: Troy
  email: Troy@foothillsmachinery.com
  url: foothillsmachinery.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c8ce19a6-f4cf-4a5b-bc7b-557e727ad083.png
name: Foothills Machinery Sales
navigation:
  - name: HURCO
    id: db864e24-b8d7-4c0a-a955-93dff4a2cd68
    type: content
title: Machine Tools for the Metalworking Industry
