typography_spectrum: 0.016026374883949757
color:
  brandStrength: 0.14469292643480003
  lightness: 0.6540206922218204
  saturation: 0.7852568810340017
  rhythmicContrast: 0.19780602352693677
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
layout_spectrum: 0.992014474933967
author:
  name: Troy
  email: Troy@foothillsmachinery.com
  url: foothillsmachinery.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c8ce19a6-f4cf-4a5b-bc7b-557e727ad083.png
name: Foothills Machinery Sales
navigation:
  - name: HURCO
    id: db864e24-b8d7-4c0a-a955-93dff4a2cd68
    type: content
title: Machine Tools for the Metalworking Industry
